apiVersion: v1
kind: Pod
metadata:
  name: multi-containers
  namespace: roboshop
  loables:
    environment: dev
  specs:
  containers: 
  - name: nginx
    image: nginx
  - nmae: almalinux
    image: almalinux
    commands: ["sleep","1000"]
