apiVersion: v1
kind: Pod
metadata:
  name: multi-containers
  namespace: roboshop
  labels:
    environment: dev
spec:
  containers: 
  - name: nginx
    image: nginx
  - name: almalinux
    image: almalinux:9
    command: ["sleep","1000"]