apiVersion: v1
kind: Pod
metadata:
  name: config-map-demo
  namespace: roboshop
  labels:
    environment: dev
spec:
  containers: 
    - name: nginx
      image: nginx
  envFrom:
    - configMapRef:
        name: pod-config