apiVersion: v1
kind: Service
metadata:
  name: nginx 
spec:
  selector:
    project: roboshop
    environment: dev
    component: frontend
ports:
    - protocol: TCP
      port: 80
      targetPort: 80